<template>
	<setup-step>
		<template v-slot:info>
			<div class="setup-icon">
				<icon icon="wallet" />
			</div>
			<h3>It looks like you don't have a wallet yet!</h3>
			<transition name="fade" mode="out-in">
				<p v-if="mode === 'create-wallet'" key="create-wallet">Enter a strong password to
					encrypt your new wallet. You will use this to unlock your wallet. A unique seed
					will be generated by Sia which you can use to recover your wallet</p>
				<p v-else-if="mode === 'recover-wallet'" key="create-wallet">Enter your 29 word seed to
					recover your wallet and a strong password to encrypt your wallet. You will use
					this to unlock your wallet.</p>
				<p v-else-if="mode === 'review'" key="review">Below Sia has generated a unique 29
					word seed. Please store this in a safe place. It can be used to recover your
					funds if you ever lose access to your wallet.</p>
				<p v-else key="ask">Would you like to create a brand new wallet for this host or
					recover your wallet from a seed? It is recommended to use a seed different
					from your primary wallet for your host. Hosts on different devices cannot use
					the same seed, each host needs a unique seed.</p>
			</transition>
		</template>
		<transition name="fade" mode="out-in">
			<div class="create-wallet" v-if="mode === 'create-wallet'" key="create">
				<div class="control">
					<label>Unlock Password</label>
					<input type="password" v-model="unlockPassword" />
				</div>
				<p>Hosts need to have their wallet unlocked at all times in order to form contracts
					and submit storage proofs. Sia Host Manager can automatically unlock your wallet
					for you.</p>
				<div class="control">
					<input type="checkbox" v-model="autoUnlock" id="chk-auto-unlock-create" />
					<label for="chk-auto-unlock-create">Automatically Unlock</label>
				</div>
			</div>
			<div class="recover-wallet" v-else-if="mode === 'recover-wallet'" key="recover">
				<div class="review-wallet">
					<div class="control">
						<label>Wallet Seed</label>
						<textarea v-model="recoverSeed"></textarea>
					</div>
					<div class="review-controls">
						<button @click="onLoadSeed" class="btn btn-inline pull-right"><icon icon="save" /> Load</button>
					</div>
				</div>
				<div class="control">
					<label>Unlock Password</label>
					<input type="password" v-model="unlockPassword" />
				</div>
				<p>Hosts need to have their wallet unlocked at all times in order to form contracts
					and submit storage proofs. Sia Host Manager can automatically unlock your wallet
					for you.</p>
				<div class="control">
					<input type="checkbox" v-model="autoUnlock" id="chk-auto-unlock-review" />
					<label for="chk-auto-unlock-review">Automatically Unlock</label>
				</div>
			</div>
			<div class="review-wallet" v-else-if="mode === 'review'" key="review">
				<div class="control">
					<textarea v-model="seed" readonly></textarea>
				</div>
				<div class="review-controls">
					<button @click="onSaveSeed" class="btn btn-inline pull-right" :disabled="saving"><icon icon="save" /> Save</button>
				</div>
			</div>
			<div class="buttons" v-else key="ask">
				<button class="btn btn-inline btn-success" @click="mode='create-wallet'">Create New Wallet (Recommended)</button>
				<button class="btn btn-inline" @click="mode='recover-wallet'">Recover From Seed</button>
			</div>
		</transition>
		<template v-slot:controls>
			<transition mode="out-in" name="fade" appear>
				<button v-if="mode !== null" class="btn btn-success btn-inline" @click="onWalletClick" :key="createText" :disabled="walletDisabled">{{ createText }}</button>
			</transition>
		</template>
	</setup-step>
</template>

<script>
import { promises as fs } from 'fs';
import log from 'electron-log';
import { mapState, mapActions } from 'vuex';
import { decode } from '@stablelib/utf8';

import SiaApiClient from '@/api/sia';
import { showSaveDialogAsync, showOpenDialogAsync } from '@/utils';

import SetupStep from './SetupStep';

export default {
	components: {
		SetupStep
	},
	props: {
		config: Object
	},
	data() {
		return {
			saving: false,
			creating: false,
			autoUnlock: false,
			mode: null,
			unlockPassword: null,
			recoverSeed: null,
			seed: null
		};
	},
	computed: {
		...mapState({
			appConfig: state => state.config
		}),
		createText() {
			switch (this.mode) {
			case 'create-wallet':
				return 'Create Wallet';
			case 'recover-wallet':
				return 'Recover Wallet';
			default:
				return 'Done';
			}
		},
		walletDisabled() {
			if (this.creating)
				return true;

			if (this.mode === 'review')
				return false;

			if (this.mode === 'create-wallet')
				return !this.unlockPassword || this.unlockPassword.length === 0;

			return !this.unlockPassword || !this.recoverSeed || this.recoverSeed.trim().split(' ').length !== 29 || this.unlockPassword.length === 0;
		}
	},
	mounted() {
		this.walletPassword = this.config.siad_wallet_password || '';
	},
	methods: {
		...mapActions(['pushNotification']),
		async onWalletClick() {
			if (this.creating)
				return;

			try {
				this.creating = true;

				switch (this.mode) {
				case 'create-wallet':
					await this.createWallet();
					break;
				case 'recover-wallet':
					await this.recoverWallet();
					break;
				case 'review':
					const config = {};

					if (this.autoUnlock)
						config.siad_wallet_password = this.unlockPassword;

					this.$emit('done', {
						inc: 1,
						config
					});
					break;
				}
			} catch (ex) {
				log.error('create wallet step on click', ex.message);
				this.pushNotification({
					message: ex.message,
					icon: 'wallet',
					severity: 'danger'
				});
			} finally {
				this.creating = false;
			}
		},
		async onLoadSeed() {
			if (this.saving)
				return;

			try {
				this.saving = true;

				const filePaths = await showOpenDialogAsync({
					title: 'Load Wallet Seed',
					buttonLabel: 'Load Seed',
					filters: [
						{ name: 'Seed File', extensions: ['seed'] },
						{ name: 'All Files', extensions: ['*'] }
					]
				});

				if (!Array.isArray(filePaths) || filePaths.length === 0)
					return;

				const seed = await fs.readFile(filePaths[0]);

				this.recoverSeed = decode(seed);
			} catch (ex) {
				log.error('create wallet onLoadSeed', ex.message);
				this.pushNotification({
					message: ex.message,
					icon: 'save',
					severity: 'danger'
				});
			}
		},
		async onSaveSeed() {
			if (this.saving)
				return;

			try {
				this.saving = true;

				const filePath = await showSaveDialogAsync({
					title: 'Save Wallet Seed',
					defaultPath: 'my-wallet.seed',
					buttonLabel: 'Save Seed',
					filters: [
						{ name: 'Seed File', extensions: ['seed'] },
						{ name: 'All Files', extensions: ['*'] }
					]
				});

				if (!filePath)
					return;

				await fs.writeFile(filePath, this.seed);
			} catch (ex) {
				log.error('create wallet on save seed click', ex.message);
				this.pushNotification({
					message: ex.message,
					icon: 'save',
					severity: 'danger'
				});
			} finally {
				this.saving = false;
			}
		},
		async createWallet() {
			const client = new SiaApiClient(this.appConfig),
				resp = await client.createWallet(this.unlockPassword);

			if (resp.statusCode !== 200)
				throw new Error(resp.body.message || 'Error creating wallet');

			this.seed = resp.body.primaryseed;
			this.mode = 'review';
		},
		async recoverWallet() {
			this.recoverSeed = this.recoverSeed.trim();

			const client = new SiaApiClient(this.appConfig),
				resp = await client.recoverWallet(this.recoverSeed, this.unlockPassword);

			if (resp.statusCode !== 200)
				throw new Error(resp.body.message || 'Error recovering seed');

			this.seed = resp.body.primaryseed;
			this.mode = 'review';
		}
	}
};
</script>

<style lang="stylus" scoped>
.buttons {
	text-align: center;
}

.review-wallet {
	display: grid;
	grid-template-columns: minmax(0, 1fr) auto;
	grid-gap: 15px;
	align-items: center;
	margin-bottom: 15px;

	.control {
		margin: 0;
	}

	.review-controls {
		text-align: right;
	}

	p {
		margin: 0;
	}

	.btn {
		margin: 0;
	}
}
</style>
